version: "3.3"

services:
  filebeat:
    image: 'filebeat:${TAG-latest}'
    env_file:
      - .env
    build:
      context: ./filebeat
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
