version: "3.3"

services:
  filebeat:
    image: 'filebeat:${TAG-latest}'
    depends_on:
      - backend
    env_file:
      - .env
#    environment:
#      - SERVER_NAME=${DOMAIN?Variable not set}
#      - SERVER_HOST=https://${DOMAIN?Variable not set}
#      # Allow explicit env var override for tests
#      - SMTP_HOST=${SMTP_HOST}
    build:
      context: ./backend
      dockerfile: filebeat.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
#    deploy:
#      labels:
#        - traefik.enable=true
#        - traefik.constraint-label-stack=${TRAEFIK_TAG?Variable not set}
#        - traefik.http.routers.${STACK_NAME?Variable not set}-backend-http.rule=PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`)
#        - traefik.http.services.${STACK_NAME?Variable not set}-backend.loadbalancer.server.port=80
    networks:
      - default
