version: "3.3"

services:
  btcpool:
    image: ${DOCKER_IMAGE_BTCPOOL}:${TAG_BTCPOOL}
    ports:
      - "1800:1800" # sserver
      - "8080:8080" # statshttpd
      - "8081:8081" # slparserhttpd
      - "9101:9101"
#    expose:
#      - 9101
    depends_on:
      - zookeeper
      - kafka
      - miner-list
    volumes:
      - "./btcpool/config:/work/config"
    restart: always
    command: ["sserver", "-c", "/work/config/sserver.cfg"]
    networks:
      - default
      - monitor-net

  ckb-node:
    image: "nervos/ckb"
    ports: 
      - "8114:8114" # RPC
      - "8115:8115" # Blockchain
    environment:
      CKB_CHAIN: "mainnet"
    volumes:
      - "./ckb-node:/var/lib/ckb"
    command: ["run"]

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    ports:
      - "127.0.0.1:2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - default
    logging:
      driver: none

  kafka:
    image: confluentinc/cp-kafka:5.5.1
    depends_on:
      - zookeeper
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka:9092"
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - default
    logging:
      driver: none

  miner-list:
    build: ./miner-list
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      MINER_LIST_FILE_PATH: "${MINER_LIST_FILE_PATH}"
    networks:
      - default
    restart: always
    depends_on:
      - mysql
    volumes:
      - ${MINER_LIST_FILE_PATH}:/root/config/miners.json

  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --log-error=/var/log/mysql/mysql.log
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - ./mysql/log:/var/log/mysql
    restart: always
    logging:
      driver: none

  # only run redis if enabled in btcpool
  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis/data/db:/data/db
    networks:
      - default
    logging:
      driver: none
