global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert_rules.yaml"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'btcpoolexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['btcpool:9101']

  - job_name: 'ckbnodeexporter'
    scrape_interval: 5s
    metrics_path: '/'
    static_configs:
      - targets: ['ckb-node:8100']

  - job_name: 'kafkaexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['kafkaexporter:9308']

  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:9080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
